### ISSUE TITLE
new configparser==3.5.2 does not honor pytest-flake8 configuration

### ISSUE THREAD

**Issue by sahumada** [jaraco/configparser#28] opened 2019-01-25 12:14 UTC
my CI got broken after the configparser==5.3.2 release today when using tox.ini to configure pytest-flake8. 

for some reason, the tox.ini configuration to ignore E501 does not work now and it gets reported as an error. configparser==3.5.1 works as expected. 

all other modules have not changed.

--error--
`my_file.py:15:80: E501 line too long (87 > 79 characters) `

--versions--
`python==2.7.2,apipkg==1.5,astroid==1.4.9,atomicwrites==1.2.1,attrs==18.2.0,backports.functools-lru-cache==1.5,configparser==3.5.2,coverage==4.5.2,enum34==1.1.6,execnet==1.5.0,flake8==3.5.0,formic==0.9b8,funcsigs==1.0.2,futures==3.2.0,isort==4.3.4,jenkinsapi==0.3.3,junit-xml==1.7,lazy-object-proxy==1.3.1,mccabe==0.6.1,mock==1.0.0,more-itertools==5.0.0,pluggy==0.7.1,psutil==5.1.3,py==1.7.0,pycodestyle==2.3.1,pyflakes==1.6.0,Pygments==2.2.0,pylint==1.6.5,pytest==3.6.4,pytest-cov==2.5.1,pytest-flake8==1.0.2,pytest-forked==1.0.1,pytest-pylint==0.12.0,pytest-xdist==1.22.5,pytz==2018.9,requests==2.13.0,retrying==1.3.3,six==1.12.0,suds==0.4,wrapt==1.11.1,xmltodict==0.10.2`

--tox.ini--
```
[flake8]
# C901 '*' is too complex
# E402 module level import not at top of file
# E501 line too long
exclude = {[base]exclude}
ignore = C901,E402,E501
max-complexity = 10
max-line-length = 160
norecursedirs = {[base]norecursedirs}

[pytest]
markers =
    flake8
    pylint
deps =
    {[testenv:pytest]deps}
python_files = test_*.py

[testenv:flake8]
commands =
    pytest -v --cache-clear \
    --flake8 \
    --junitxml=test-results/pytest-flake8-result.xml \
    {posargs}
```

**Comment by klausfmh** [comment] 2019-01-25 12:42
even a simple file like:
```

[flake8]
max_line_length = 120
```

fails if used by flake8 (No issues with 3.5.1)

**Comment by hashar** [comment] 2019-01-25 13:36
Duplicate of #27

**Closed** 2019-01-25 14:08 UTC
