### ISSUE TITLE
Update README regarding dropped support for Python 2

### ISSUE THREAD

**Issue by slel** [jaraco/configparser#57] opened 2020-08-14 20:30 UTC
To wrap up dropping Python 2 support after this commit:

- 479ac2149d8 Finish dropping support for Python 2 (I hope)

the README should be updated, as it still mentions Python 2
in several places.

**Comment by jugmac00** [comment] 2020-10-08 13:57
Duplicate of #51

**Closed** 2020-10-08 21:53 UTC
